/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIexc;

import java.util.Calendar;

/**
 *
 * @author Carlos.J.Pina
 */
public class IdadeVotoB extends javax.swing.JFrame {

    /**
     * Creates new form IdadeVotoB
     */
    public IdadeVotoB() {
        initComponents();
        PainelVoto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfAnoNasc = new javax.swing.JSpinner();
        btnVotar = new javax.swing.JButton();
        PainelVoto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Idade Votação");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Idade votação");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 0));
        jLabel2.setText("Ano Nascimento:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, -1, -1));

        tfAnoNasc.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2016, 1));
        getContentPane().add(tfAnoNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 63, 139, 25));

        btnVotar.setFont(new java.awt.Font("Tekton Pro", 3, 18)); // NOI18N
        btnVotar.setForeground(new java.awt.Color(0, 153, 153));
        btnVotar.setText("Posso votar ?");
        btnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVotar, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 106, 151, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Idade: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Situação: ");

        lblIdade.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblIdade.setForeground(new java.awt.Color(0, 0, 255));
        lblIdade.setText("0");

        lblSituacao.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblSituacao.setForeground(new java.awt.Color(0, 0, 255));
        lblSituacao.setText("(vazio)");

        javax.swing.GroupLayout PainelVotoLayout = new javax.swing.GroupLayout(PainelVoto);
        PainelVoto.setLayout(PainelVotoLayout);
        PainelVotoLayout.setHorizontalGroup(
            PainelVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVotoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PainelVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(PainelVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PainelVotoLayout.setVerticalGroup(
            PainelVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVotoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PainelVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblIdade))
                .addGap(18, 18, 18)
                .addGroup(PainelVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblSituacao))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        getContentPane().add(PainelVoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 370, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarActionPerformed
        int anoNasc = Integer.parseInt(tfAnoNasc.getValue().toString());
        
        Calendar ano = Calendar.getInstance();
        int n = ano.get(Calendar.YEAR);
      
        int i = n - anoNasc;
        
        String op = "";
        
        lblIdade.setText(Integer.toString(i));
        
        PainelVoto.setVisible(true);
        
        if(i < 16){
            op = "<html>Não pode Votar!</html>";
        }else if((i >= 16 && i < 18) || i > 70){
            op = "<html>Voto Opcional!</html>";
        }else{
            op = "<html>Voto Obrigatorio !</html>";
        }
        
        lblSituacao.setText(op);
    }//GEN-LAST:event_btnVotarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdadeVotoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdadeVotoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdadeVotoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdadeVotoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdadeVotoB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelVoto;
    private javax.swing.JButton btnVotar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JSpinner tfAnoNasc;
    // End of variables declaration//GEN-END:variables
}
