/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIexc;

/**
 *
 * @author Carlos.J.Pina
 */
public class SuperCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form SuperCalculadora
     */
    public SuperCalculadora() {
        initComponents();
        
        
        lblQuadrada.setVisible(false);
        lbl_cubo.setVisible(false);
        lbl_div.setVisible(false);
        lblabsoluto.setVisible(false);
        lblcubica.setVisible(false);
        
        lblDiv_res.setVisible(false);
        lbl_cubica_res.setVisible(false);
        lbl_quadrada_res.setVisible(false);
        lblabsoluto_res.setVisible(false);
        lblcubo_res.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfvalor = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();
        lbl_div = new javax.swing.JLabel();
        lbl_cubo = new javax.swing.JLabel();
        lblQuadrada = new javax.swing.JLabel();
        lblcubica = new javax.swing.JLabel();
        lblabsoluto = new javax.swing.JLabel();
        lblDiv_res = new javax.swing.JLabel();
        lblcubo_res = new javax.swing.JLabel();
        lbl_quadrada_res = new javax.swing.JLabel();
        lbl_cubica_res = new javax.swing.JLabel();
        lblabsoluto_res = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Super Calculadora");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculadora.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Informe um valor :");

        btnCalcular.setFont(new java.awt.Font("Tekton Pro", 3, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 102, 102));
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/64px-Plataformas.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lbl_div.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        lbl_div.setForeground(new java.awt.Color(51, 51, 51));
        lbl_div.setText("Resto de divisão --------------------------> ");

        lbl_cubo.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        lbl_cubo.setForeground(new java.awt.Color(51, 51, 51));
        lbl_cubo.setText("Elevado ao cubo --------------------------->");

        lblQuadrada.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        lblQuadrada.setForeground(new java.awt.Color(51, 51, 51));
        lblQuadrada.setText("Raiz Quadrada --------------------------->");

        lblcubica.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        lblcubica.setForeground(new java.awt.Color(51, 51, 51));
        lblcubica.setText("Raiz Cubica ------------------------------->");

        lblabsoluto.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        lblabsoluto.setForeground(new java.awt.Color(51, 51, 51));
        lblabsoluto.setText("Valor absoluto --------------------------->");

        lblDiv_res.setFont(new java.awt.Font("Tekton Pro", 2, 14)); // NOI18N
        lblDiv_res.setText("0.0");

        lblcubo_res.setFont(new java.awt.Font("Tekton Pro", 2, 14)); // NOI18N
        lblcubo_res.setText("0.0");

        lbl_quadrada_res.setFont(new java.awt.Font("Tekton Pro", 2, 14)); // NOI18N
        lbl_quadrada_res.setText("0.0");

        lbl_cubica_res.setFont(new java.awt.Font("Tekton Pro", 2, 14)); // NOI18N
        lbl_cubica_res.setText("0.0");

        lblabsoluto_res.setFont(new java.awt.Font("Tekton Pro", 2, 14)); // NOI18N
        lblabsoluto_res.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(24, 24, 24)
                                        .addComponent(tfvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcubica)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_div)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDiv_res, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_cubo)
                                            .addComponent(lblQuadrada))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblcubo_res, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_cubica_res, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_quadrada_res, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblabsoluto)
                                .addGap(25, 25, 25)
                                .addComponent(lblabsoluto_res, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfvalor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(37, 37, 37)
                        .addComponent(btnCalcular)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiv_res, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_div))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_cubo)
                            .addComponent(lblcubo_res))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuadrada)
                            .addComponent(lbl_quadrada_res))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcubica)
                            .addComponent(lbl_cubica_res))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblabsoluto)
                            .addComponent(lblabsoluto_res))
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        
        float nun = Float.parseFloat(tfvalor.getValue().toString());
        
        float restD = nun % 2;
        int elevC = (int) Math.pow(nun, 3);
        float raizQ = (float) Math.sqrt(nun);
        float raizCubica  = (float) Math.cbrt(nun);
        int valorAbs = (int) Math.abs(nun);
         
        lblDiv_res.setText(Float.toString(restD));
        lbl_cubica_res.setText(Float.toString(raizCubica));
        lbl_quadrada_res.setText(String.format("%.2f", raizQ));
        
        //lblabsoluto_res.setText(Integer.toString(valorAbs));
        lblabsoluto_res.setText(String.format("%d", valorAbs));
        
        lblcubo_res.setText(Integer.toString(elevC));
        
        
        lblQuadrada.setVisible(true);
        lbl_cubo.setVisible(true);
        lbl_div.setVisible(true);
        lblabsoluto.setVisible(true);
        lblcubica.setVisible(true);
        
        lblDiv_res.setVisible(true);
        lbl_cubica_res.setVisible(true);
        lbl_quadrada_res.setVisible(true);
        lblabsoluto_res.setVisible(true);
        lblcubo_res.setVisible(true);
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDiv_res;
    private javax.swing.JLabel lblQuadrada;
    private javax.swing.JLabel lbl_cubica_res;
    private javax.swing.JLabel lbl_cubo;
    private javax.swing.JLabel lbl_div;
    private javax.swing.JLabel lbl_quadrada_res;
    private javax.swing.JLabel lblabsoluto;
    private javax.swing.JLabel lblabsoluto_res;
    private javax.swing.JLabel lblcubica;
    private javax.swing.JLabel lblcubo_res;
    private javax.swing.JSpinner tfvalor;
    // End of variables declaration//GEN-END:variables
}
